development: &default_development
  :host: 127.0.0.1
  :thread_safe: true

development_resque:
  <<: *default_development
  :db:  1

test: &default_test
  :host: 127.0.0.1
  :db:  <%= 10 + ENV['TEST_ENV_NUMBER'].to_i %>
  :thread_safe: true

test_resque:
  <<: *default_test
  :db:  <%= 40 + ENV['TEST_ENV_NUMBER'].to_i %>

release: &default_release
  :host: release1
  :thread_safe: true

release_resque:
  <<: *default_release
  :db:  1

hotfix: &default_hotfix
  :host: hotfix1
  :thread_safe: true

hotfix_resque:
  <<: *default_hotfix
  :db:  1

production:
  :host: redis
  :pool_size: 30
  :db:  3
  :thread_safe: true

production_resque:
  :host: resque
  :thread_safe: true
  :port: 6380
